"""empty message

Revision ID: 53ff282aafc2
Revises: ad0735de426f
Create Date: 2024-05-05 19:13:19.649664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53ff282aafc2'
down_revision: Union[str, None] = 'ad0735de426f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('type', sa.Enum('CAT', 'DOG', name='imagetypes'), server_default='DOG', nullable=False))
    op.drop_column('image', 'image_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('image_type', postgresql.ENUM('CAT', 'DOG', name='imagetypes'), server_default=sa.text("'DOG'::imagetypes"), autoincrement=False, nullable=False))
    op.drop_column('image', 'type')
    # ### end Alembic commands ###
